---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    chart: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: {{ .Values.name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        ports:
          - containerPort: 8080
